# Generated by Django 3.1.7 on 2021-04-18 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('isCompany', models.BooleanField(default=True)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('place', models.CharField(max_length=128)),
                ('duration', models.CharField(max_length=128)),
                ('stipend', models.CharField(max_length=128)),
                ('apply_by', models.DateField()),
                ('no_of_openings', models.IntegerField()),
                ('perks', models.CharField(max_length=128)),
                ('skills', models.CharField(max_length=128)),
                ('about_internship', models.TextField()),
                ('who_can_apply', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='company.company')),
            ],
            options={
                'verbose_name': 'Internship',
                'verbose_name_plural': 'Internships',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('mob', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('no_of_employees', models.IntegerField(default=0, null=True)),
                ('internship_post', models.IntegerField(default=0, null=True)),
                ('interns_hired', models.IntegerField(default=0, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InternshipAppliedDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(default='', max_length=128)),
                ('student_email', models.EmailField(default=True, max_length=254, null=True)),
                ('student_mob', models.CharField(blank=True, max_length=10, null=True)),
                ('matching', models.DecimalField(decimal_places=2, default=True, max_digits=5, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliedInternship', to='company.internship')),
            ],
        ),
    ]
