# Generated by Django 3.1.7 on 2021-04-18 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplieddb',
            name='applied_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipapplieddb',
            name='internshipkey',
            field=models.IntegerField(default=12),
        ),
    ]
