# Generated by Django 3.1.7 on 2021-04-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210418_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='no_of_applicants',
            field=models.IntegerField(null=True),
        ),
    ]
