# Generated by Django 3.1.7 on 2021-04-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_internship_apply_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipAppliedDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('internship_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=30)),
            ],
        ),
    ]
