# Generated by Django 3.1.7 on 2021-04-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_internshipapplieddb'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplieddb',
            name='matching',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplieddb',
            name='student_email',
            field=models.EmailField(default=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplieddb',
            name='student_mob',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplieddb',
            name='student_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
