# Generated by Django 3.1.7 on 2021-04-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210331_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='student/resume/'),
        ),
    ]
