# Generated by Django 3.1.7 on 2021-04-28 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210428_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='auth_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
